### ISSUE TITLE
Key error when more than one portal

### ISSUE THREAD

**Issue by bakerac4** [jeremybarbet/react-native-portalize#2] opened 2020-06-05 14:21 UTC
Im getting a duplicate key error when I have more than one portal. It seems that the key for both is 0.

**Comment by jeremybarbet** [comment] 2020-06-11 14:08
Hey!

Do you have a reproduction code, I did that and didn't get any errors/warnings

```tsx
<Host style={styles.container}>
  <Text>Open up App.js to start working on your app!</Text>

  <Portal>
    <Text>A portal on top of the rest</Text>
  </Portal>

  <Portal>
    <Text>A portal on top of the rest</Text>
  </Portal>
</Host>
```

**Comment by bakerac4** [comment] 2020-06-12 18:13
@jeremybarbet While I don't have a reproduction I can share, I did some research into this and it seems to be related to navigation. Im using react-navigation - and I noticed in your examples that you have all examples on a single screen. Im thinking it might be related to having them on two different screens. I have two modals loading in one tab, and get no error but when I click on another tab and to go that screen I then get the key error

**Comment by jeremybarbet** [comment] 2020-06-16 08:12
Alright, I did try with react-navigation.

```bash
expo init example
> tabs (using react-navigation)
```

In the two tab screens (LinksScreen, HomeScreen) I added one Host and one Portal for each screen and got no error.

Unless you provide a reproduction case, I'm afraid I can't help any further.

**Comment by andres-pino** [comment] 2020-06-19 14:32
I'm getting the same error.
I am using react navigation v5 and the Host component is wrapping all the NavigationContainer. I have a StackNavigator and a DrawerNavigator, the Portal is used along different Screens between this navigators. Unfortunately I am not allowed to share my code and I don't have the time to reproduce it.

**Comment by eongjun** [comment] 2020-06-25 05:15
I'm getting the same error.
In my code, I'm using react navigation v5, and a tab navigator is nested inside a stack navigator.

1. Host component is wrapping Tab Navigator
When two different screens inside the tab Navigator have portal each, key error occurs.

2. Host component is wrapping all the Navigation Container
When two different screens inside the tab Navigator have portal each, key error does not occur.
But in android, modalize component cannot be swipe.

**Comment by archansel** [comment] 2020-06-28 19:44
I got the error too using react navigation v5

my case is Host component wrapping root navigator (stack) which has tab navigator, something like this `NavigationContainer > Host > Stack.Navigator > Tab.Navigator > MyScreen > Portal`

I create a modal class that include the portal, so each modal have one portal. In one of my screen I have two modal, something like this
```
<View>
  <Portal><Modal/></Portal>
  <Portal><Modal/></Portal>
  <View>...</View>
</View>
```

strangely I can't exactly reproduce the error because its kind of random

**Comment by hansen-simon** [comment] 2020-06-30 12:37
I get the same error. And I'm using a similar structure with react-navigation as @archansel described. 

I hat a look into the code and I thing the problem might be that the key is just set to the portal index number. Other libraries might do the same and therefor the key might not be unique. 
I replace `key={key}` with 
```
      key={`portalize_portal_${key}`}
```
int the src/Manager.tsx file and the error is gone for me. ([fork](https://github.com/digital-h-gmbh/react-native-portalize/tree/digital-h-fork))

**Comment by brycepavey** [comment] 2020-07-03 01:35
I implemented solution from @hansen-simon but was still getting duplicate key errors. I replaced the `key` with `index` to fix.

Manager.js:
```
return portals.map(({ key, children }, index) => (
    <View key={`${index}`} collapsable={false} pointerEvents="box-none" style={StyleSheet.absoluteFill}>
      {children}
    </View>
  ));
```

**Comment by jeremybarbet** [comment] 2020-07-25 10:08
Hey,

Can you check if the new release `1.0.4` fix the key issues?

**Comment by teenoh** [comment] 2020-07-25 19:35
I just upgraded to `1.0.4` and no longer see the error

**Comment by jeremybarbet** [comment] 2020-07-27 07:44
Sounds good I will close this issue then 🙌🏻

**Closed by jeremybarbet** 2020-07-27 07:44 UTC
